GET http://localhost:4000/products/create


###

GET http://localhost:4000/products


###

PATCH http://localhost:4000/products/65a3a4c7e6f7db87090c405a/cartFlag

###

GET http://localhost:4000/products/gomu-gomu-no-hoodie

### 

GET http://localhost:4000/cart

###

POST http://localhost:4000/cart
Content-Type: application/json

{
    "product" : "65a3a4c7e6f7db87090c405a",
    "quantity" : 8
}


### 

PATCH http://localhost:4000/cart/65a40e841cec3cd7efa70e4e
Content-Type: application/json

{
    "quantity": 6
}


###

DELETE http://localhost:4000/cart

###

DELETE http://localhost:4000/cart/65a555a3d3bb5d4fba76f2e9/p/65a3a4c7e6f7db87090c405a

###

PUT http://localhost:4000/cart
Content-Type: application/json

{
    "items" : [
        {
            "id": "65ef4b46c3c37bbd9aa86233",
            "quantity": "5"
        }, 
        {
          "id" : "65effddbeead2df375dbafa7",
          "quantity" : "3"
        }
    ]
}

###
  
POST http://localhost:4000/products/filter
Content-Type: application/json

{
    "searchStr" : "manga"
}
